/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.bluethunder.tar2.ui.auth.model

import com.huawei.agconnect.cloud.database.CloudDBZoneObject
import com.huawei.agconnect.cloud.database.annotations.Indexes
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys

@PrimaryKeys("id")
@Indexes("email:email", "id:id")
class UserModel : CloudDBZoneObject(UserModel::class.java) {
    var id: String? = null
    var email: String? = null
    var pushToken: String? = null
    var name: String? = null

    companion object {
        const val ID = "id"
        const val EMAIL = "email"
        const val PUSH_TOKEN = "pushToken"
        const val NAME = "name"
    }

    override fun toString(): String {
        return "UserModel(id=$id, email=$email, pushToken=$pushToken, name=$name)"
    }
}
