/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.bluethunder.tar2.ui.auth.model

import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys
import com.huawei.agconnect.cloud.database.CloudDBZoneObject
import com.bluethunder.tar2.ui.auth.model.UserModel

/**
 * Definition of ObjectType UserModel.
 *
 * @since 2022-07-15
 */
@PrimaryKeys("id")
class UserModel : CloudDBZoneObject(UserModel::class.java) {
    var id: String? = null
    var email: String? = null
    var pushToken: String? = null
    var name: String? = null

    override fun toString(): String {
        return "UserModel(id=$id, email=$email, pushToken=$pushToken, name=$name)"
    }
}